INSERT INTO KeyList (id, modificationCounter, business_key, disabled, ordering, cacheable, name, valueRequired, valuePattern, permission, comment) VALUES (1, 0, 'country', 0, 0, 1, 'Country', 1, '[A-Z]{3}', null, 'Countries of the world');

INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000020, 0, 1, 0, 'AD', 'AND', 'Andorra', 'Principality of Andorra');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000784, 0, 1, 0, 'AE', 'ARE', 'United Arab Emirates', 'United Arab Emirates');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000004, 0, 1, 0, 'AF', 'AFG', 'Afghanistan', 'Islamic State of Afghanistan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000028, 0, 1, 0, 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua and Barbuda');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000660, 0, 1, 0, 'AI', 'AIA', 'Anguilla', 'Anguilla');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000008, 0, 1, 0, 'AL', 'ALB', 'Albania', 'Republic of Albania');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000051, 0, 1, 0, 'AM', 'ARM', 'Armenia', 'Republic of Armenia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000024, 0, 1, 0, 'AO', 'AGO', 'Angola', 'Republic of Angola');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000010, 0, 1, 0, 'AQ', 'ATA', 'Antarctica', 'Antarctica');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000032, 0, 1, 0, 'AR', 'ARG', 'Argentina', 'Argentine Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000016, 0, 1, 0, 'AS', 'ASM', 'American Samoa', 'Territory of American Samoa');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000040, 0, 1, 0, 'AT', 'AUT', 'Austria', 'Republic of Austria');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000036, 0, 1, 0, 'AU', 'AUS', 'Australia', 'Commonwealth of Australia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000533, 0, 1, 0, 'AW', 'ABW', 'Aruba', 'Aruba');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000248, 0, 1, 0, 'AX', 'ALA', 'Åland Islands', 'Åland Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000031, 0, 1, 0, 'AZ', 'AZE', 'Azerbaijan', 'Republic of Azerbaijan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000070, 0, 1, 0, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000052, 0, 1, 0, 'BB', 'BRB', 'Barbados', 'Barbados');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000050, 0, 1, 0, 'BD', 'BGD', 'Bangladesh', 'Peoples Republic of Bangladesh');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000056, 0, 1, 0, 'BE', 'BEL', 'Belgium', 'Kingdom of Belgium');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000854, 0, 1, 0, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000100, 0, 1, 0, 'BG', 'BGR', 'Bulgaria', 'Republic of Bulgaria');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000048, 0, 1, 0, 'BH', 'BHR', 'Bahrain', 'Kingdom of Bahrain');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000108, 0, 1, 0, 'BI', 'BDI', 'Burundi', 'Republic of Burundi');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000204, 0, 1, 0, 'BJ', 'BEN', 'Benin', 'Republic of Benin');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000652, 0, 1, 0, 'BL', 'BLM', 'Saint Barthélemy', 'Saint Barthélemy');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000060, 0, 1, 0, 'BM', 'BMU', 'Bermuda', 'Bermuda');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000096, 0, 1, 0, 'BN', 'BRN', 'Brunei Darussalam', 'Negara Brunei Darussalam');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000068, 0, 1, 0, 'BO', 'BOL', 'Bolivia', 'Plurinational State of Bolivia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000535, 0, 1, 0, 'BQ', 'BES', 'Bonaire', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000076, 0, 1, 0, 'BR', 'BRA', 'Brazil', 'Federative Republic of Brazil');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000044, 0, 1, 0, 'BS', 'BHS', 'Bahamas', 'Commonwealth of The Bahamas');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000064, 0, 1, 0, 'BT', 'BTN', 'Bhutan', 'Kingdom of Bhutan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000074, 0, 1, 0, 'BV', 'BVT', 'Bouvet Island', 'Bouvet Island');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000072, 0, 1, 0, 'BW', 'BWA', 'Botswana', 'Republic of Botswana');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000112, 0, 1, 0, 'BY', 'BLR', 'Belarus', 'Republic of Belarus');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000084, 0, 1, 0, 'BZ', 'BLZ', 'Belize', 'Belize');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000124, 0, 1, 0, 'CA', 'CAN', 'Canada', 'Canada');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000166, 0, 1, 0, 'CC', 'CCK', 'Cocos Islands', 'Territory of Cocos (Keeling) Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000180, 0, 1, 0, 'CD', 'COD', 'Democratic Republic of Congo', 'Democratic Republic of the Congo');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000140, 0, 1, 0, 'CF', 'CAF', 'Central African Republic', 'Central African Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000178, 0, 1, 0, 'CG', 'COG', 'Congo', 'Republic of the Congo');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000756, 0, 1, 0, 'CH', 'CHE', 'Switzerland', 'Swiss Confederation');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000384, 0, 1, 0, 'CI', 'CIV', 'Côte d''Ivoire', 'Republic of Cote d''Ivoire');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000184, 0, 1, 0, 'CK', 'COK', 'Cook Islands', 'Cook Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000152, 0, 1, 0, 'CL', 'CHL', 'Chile', 'Republic of Chile');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000120, 0, 1, 0, 'CM', 'CMR', 'Cameroon', 'Republic of Cameroon');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000156, 0, 1, 0, 'CN', 'CHN', 'China', 'Peoples Republic of China');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000170, 0, 1, 0, 'CO', 'COL', 'Colombia', 'Republic of Colombia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000188, 0, 1, 0, 'CR', 'CRI', 'Costa Rica', 'Republic of Costa Rica');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000192, 0, 1, 0, 'CU', 'CUB', 'Cuba', 'Republic of Cuba');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000132, 0, 1, 0, 'CV', 'CPV', 'Cabo Verde', 'Republic of Cape Verde');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000531, 0, 1, 0, 'CW', 'CUW', 'Curaçao', 'Curaçao');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000162, 0, 1, 0, 'CX', 'CXR', 'Christmas Island', 'Territory of Christmas Island');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000196, 0, 1, 0, 'CY', 'CYP', 'Cyprus', 'Republic of Cyprus');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000203, 0, 1, 0, 'CZ', 'CZE', 'Czechia', 'Czechia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000276, 0, 1, 0, 'DE', 'DEU', 'Germany', 'Federal Republic of Germany');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000262, 0, 1, 0, 'DJ', 'DJI', 'Djibouti', 'Republic of Djibouti');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000208, 0, 1, 0, 'DK', 'DNK', 'Denmark', 'Kingdom of Denmark');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000212, 0, 1, 0, 'DM', 'DMA', 'Dominica', 'Commonwealth of Dominica');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000214, 0, 1, 0, 'DO', 'DOM', 'Dominican Republic', 'Dominican Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000012, 0, 1, 0, 'DZ', 'DZA', 'Algeria', 'Peoples Democratic Republic of Algeria');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000218, 0, 1, 0, 'EC', 'ECU', 'Ecuador', 'Republic of Ecuador');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000233, 0, 1, 0, 'EE', 'EST', 'Estonia', 'Republic of Estonia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000818, 0, 1, 0, 'EG', 'EGY', 'Egypt', 'Arab Republic of Egypt');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000732, 0, 1, 0, 'EH', 'ESH', 'Western Sahara', 'Western Sahara');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000232, 0, 1, 0, 'ER', 'ERI', 'Eritrea', 'State of Eritrea');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000724, 0, 1, 0, 'ES', 'ESP', 'Spain', 'Kingdom of Spain');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000231, 0, 1, 0, 'ET', 'ETH', 'Ethiopia', 'Federal Democratic Republic of Ethiopia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000246, 0, 1, 0, 'FI', 'FIN', 'Finland', 'Republic of Finland');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000242, 0, 1, 0, 'FJ', 'FJI', 'Fiji', 'Republic of the Fiji Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000238, 0, 1, 0, 'FK', 'FLK', 'Falkland Islands', 'Falkland Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000583, 0, 1, 0, 'FM', 'FSM', 'Micronesia', 'Federated States of Micronesia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000234, 0, 1, 0, 'FO', 'FRO', 'Faroe Islands', 'Faroe Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000250, 0, 1, 0, 'FR', 'FRA', 'France', 'French Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000266, 0, 1, 0, 'GA', 'GAB', 'Gabon', 'Gabonese Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000826, 0, 1, 0, 'GB', 'GBR', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000308, 0, 1, 0, 'GD', 'GRD', 'Grenada', 'Grenada');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000268, 0, 1, 0, 'GE', 'GEO', 'Georgia', 'Republic of Georgia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000254, 0, 1, 0, 'GF', 'GUF', 'French Guiana', 'Overseas Region of Guiana');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000831, 0, 1, 0, 'GG', 'GGY', 'Guernsey', 'Bailiwick of Guernsey');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000288, 0, 1, 0, 'GH', 'GHA', 'Ghana', 'Republic of Ghana');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000292, 0, 1, 0, 'GI', 'GIB', 'Gibraltar', 'Gibraltar');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000304, 0, 1, 0, 'GL', 'GRL', 'Greenland', 'Greenland');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000270, 0, 1, 0, 'GM', 'GMB', 'Gambia', 'Republic of The Gambia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000324, 0, 1, 0, 'GN', 'GIN', 'Guinea', 'Republic of Guinea');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000312, 0, 1, 0, 'GP', 'GLP', 'Guadeloupe', 'Overseas Region of Guadeloupe');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000226, 0, 1, 0, 'GQ', 'GNQ', 'Equatorial Guinea', 'Republic of Equatorial Guinea');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000300, 0, 1, 0, 'GR', 'GRC', 'Greece', 'Hellenic Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000239, 0, 1, 0, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000320, 0, 1, 0, 'GT', 'GTM', 'Guatemala', 'Republic of Guatemala');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000316, 0, 1, 0, 'GU', 'GUM', 'Guam', 'Territory of Guam');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000624, 0, 1, 0, 'GW', 'GNB', 'Guinea-Bissau', 'Republic of Guinea-Bissau');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000328, 0, 1, 0, 'GY', 'GUY', 'Guyana', 'Co-operative Republic of Guyana');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000344, 0, 1, 0, 'HK', 'HKG', 'Hong Kong', 'Hong Kong Special Administrative Region');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000334, 0, 1, 0, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Territory of Heard Island and McDonald Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000340, 0, 1, 0, 'HN', 'HND', 'Honduras', 'Republic of Honduras');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000191, 0, 1, 0, 'HR', 'HRV', 'Croatia', 'Republic of Croatia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000332, 0, 1, 0, 'HT', 'HTI', 'Haiti', 'Republic of Haiti');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000348, 0, 1, 0, 'HU', 'HUN', 'Hungary', 'Republic of Hungary');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000360, 0, 1, 0, 'ID', 'IDN', 'Indonesia', 'Republic of Indonesia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000372, 0, 1, 0, 'IE', 'IRL', 'Ireland', 'Ireland');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000376, 0, 1, 0, 'IL', 'ISR', 'Israel', 'State of Israel');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000833, 0, 1, 0, 'IM', 'IMN', 'Isle of Man', 'Isle of Man');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000356, 0, 1, 0, 'IN', 'IND', 'India', 'Republic of India');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000086, 0, 1, 0, 'IO', 'IOT', 'British Indian Ocean Territory', 'British Indian Ocean Territory');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000368, 0, 1, 0, 'IQ', 'IRQ', 'Iraq', 'Republic of Iraq');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000364, 0, 1, 0, 'IR', 'IRN', 'Iran', 'Islamic Republic of Iran');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000352, 0, 1, 0, 'IS', 'ISL', 'Iceland', 'Republic of Iceland');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000380, 0, 1, 0, 'IT', 'ITA', 'Italy', 'Italian Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000832, 0, 1, 0, 'JE', 'JEY', 'Jersey', 'Bailiwick of Jersey');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000388, 0, 1, 0, 'JM', 'JAM', 'Jamaica', 'Jamaica');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000400, 0, 1, 0, 'JO', 'JOR', 'Jordan', 'Hashemite Kingdom of Jordan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000392, 0, 1, 0, 'JP', 'JPN', 'Japan', 'Japan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000404, 0, 1, 0, 'KE', 'KEN', 'Kenya', 'Republic of Kenya');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000417, 0, 1, 0, 'KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyz Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000116, 0, 1, 0, 'KH', 'KHM', 'Cambodia', 'Kingdom of Cambodia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000296, 0, 1, 0, 'KI', 'KIR', 'Kiribati', 'Republic of Kiribati');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000174, 0, 1, 0, 'KM', 'COM', 'Comoros', 'Union of Comoros');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000659, 0, 1, 0, 'KN', 'KNA', 'St. Kitts and Nevis', 'Federation of Saint Kitts and Nevis');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000408, 0, 1, 0, 'KP', 'PRK', 'North-Korea', 'Democratic People''s Republic of Korea');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000410, 0, 1, 0, 'KR', 'KOR', 'South-Korea', 'Republic of Korea');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000414, 0, 1, 0, 'KW', 'KWT', 'Kuwait', 'State of Kuwait');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000136, 0, 1, 0, 'KY', 'CYM', 'Cayman Islands', 'Cayman Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000398, 0, 1, 0, 'KZ', 'KAZ', 'Kazakhstan', 'Republic of Kazakhstan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000418, 0, 1, 0, 'LA', 'LAO', 'Laos', 'Lao Peoples Democratic Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000422, 0, 1, 0, 'LB', 'LBN', 'Lebanon', 'Lebanese Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000662, 0, 1, 0, 'LC', 'LCA', 'Saint Lucia', 'Saint Lucia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000438, 0, 1, 0, 'LI', 'LIE', 'Liechtenstein', 'Principality of Liechtenstein');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000144, 0, 1, 0, 'LK', 'LKA', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000430, 0, 1, 0, 'LR', 'LBR', 'Liberia', 'Republic of Liberia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000426, 0, 1, 0, 'LS', 'LSO', 'Lesotho', 'Kingdom of Lesotho');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000440, 0, 1, 0, 'LT', 'LTU', 'Lithuania', 'Republic of Lithuania');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000442, 0, 1, 0, 'LU', 'LUX', 'Luxembourg', 'Grand Duchy of Luxembourg');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000428, 0, 1, 0, 'LV', 'LVA', 'Latvia', 'Republic of Latvia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000434, 0, 1, 0, 'LY', 'LBY', 'Libya', 'Great Socialist Peoples Libyan Arab Jamahiriya');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000504, 0, 1, 0, 'MA', 'MAR', 'Morocco', 'Kingdom of Morocco');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000492, 0, 1, 0, 'MC', 'MCO', 'Monaco', 'Principality of Monaco');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000498, 0, 1, 0, 'MD', 'MDA', 'Moldova', 'Republic of Moldova');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000499, 0, 1, 0, 'ME', 'MNE', 'Montenegro', 'Republic of Montenegro');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000663, 0, 1, 0, 'MF', 'MAF', 'Saint Martin (French part)', 'Saint Martin (French part)');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000450, 0, 1, 0, 'MG', 'MDG', 'Madagascar', 'Republic of Madagascar');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000584, 0, 1, 0, 'MH', 'MHL', 'Marshall Islands', 'Republic of the Marshall Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000807, 0, 1, 0, 'MK', 'MKD', 'North Macedonia', 'Republic of North Macedonia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000466, 0, 1, 0, 'ML', 'MLI', 'Mali', 'Republic of Mali');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000104, 0, 1, 0, 'MM', 'MMR', 'Myanmar', 'Union of Myanmar');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000496, 0, 1, 0, 'MN', 'MNG', 'Mongolia', 'Mongolia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000446, 0, 1, 0, 'MO', 'MAC', 'Macao', 'Macau Special Administrative Region');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000580, 0, 1, 0, 'MP', 'MNP', 'Northern Mariana Islands', 'Commonwealth of The Northern Mariana Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000474, 0, 1, 0, 'MQ', 'MTQ', 'Martinique', 'Overseas Region of Martinique');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000478, 0, 1, 0, 'MR', 'MRT', 'Mauritania', 'Islamic Republic of Mauritania');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000500, 0, 1, 0, 'MS', 'MSR', 'Montserrat', 'Montserrat');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000470, 0, 1, 0, 'MT', 'MLT', 'Malta', 'Republic of Malta');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000480, 0, 1, 0, 'MU', 'MUS', 'Mauritius', 'Republic of Mauritius');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000462, 0, 1, 0, 'MV', 'MDV', 'Maldives', 'Republic of Maldives');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000454, 0, 1, 0, 'MW', 'MWI', 'Malawi', 'Republic of Malawi');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000484, 0, 1, 0, 'MX', 'MEX', 'Mexico', 'United Mexican States');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000458, 0, 1, 0, 'MY', 'MYS', 'Malaysia', 'Malaysia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000508, 0, 1, 0, 'MZ', 'MOZ', 'Mozambique', 'Republic of Mozambique');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000516, 0, 1, 0, 'NA', 'NAM', 'Namibia', 'Republic of Namibia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000540, 0, 1, 0, 'NC', 'NCL', 'New Caledonia', 'New Caledonia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000562, 0, 1, 0, 'NE', 'NER', 'Niger', 'Republic of Niger');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000574, 0, 1, 0, 'NF', 'NFK', 'Norfolk Island', 'Territory of Norfolk Island');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000566, 0, 1, 0, 'NG', 'NGA', 'Nigeria', 'Federal Republic of Nigeria');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000558, 0, 1, 0, 'NI', 'NIC', 'Nicaragua', 'Republic of Nicaragua');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000528, 0, 1, 0, 'NL', 'NLD', 'Netherlands', 'Kingdom of the Netherlands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000578, 0, 1, 0, 'NO', 'NOR', 'Norway', 'Kingdom of Norway');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000524, 0, 1, 0, 'NP', 'NPL', 'Nepal', 'Nepal');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000520, 0, 1, 0, 'NR', 'NRU', 'Nauru', 'Republic of Nauru');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000570, 0, 1, 0, 'NU', 'NIU', 'Niue', 'Niue');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000554, 0, 1, 0, 'NZ', 'NZL', 'New Zealand', 'New Zealand');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000512, 0, 1, 0, 'OM', 'OMN', 'Oman', 'Sultanate of Oman');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000591, 0, 1, 0, 'PA', 'PAN', 'Panama', 'Republic of Panama');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000604, 0, 1, 0, 'PE', 'PER', 'Peru', 'Republic of Peru');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000258, 0, 1, 0, 'PF', 'PYF', 'French Polynesia', 'Overseas Country of French Polynesia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000598, 0, 1, 0, 'PG', 'PNG', 'Papua New Guinea', 'Independent State of Papua New Guinea');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000608, 0, 1, 0, 'PH', 'PHL', 'Philippines', 'Republic of the Philippines');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000586, 0, 1, 0, 'PK', 'PAK', 'Pakistan', 'Islamic Republic of Pakistan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000616, 0, 1, 0, 'PL', 'POL', 'Poland', 'Republic of Poland');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000666, 0, 1, 0, 'PM', 'SPM', 'St. Pierre and Miquelon', 'Territorial Collectivity of Saint Pierre and Miquelon');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000612, 0, 1, 0, 'PN', 'PCN', 'Pitcairn', 'Pitcairn Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000630, 0, 1, 0, 'PR', 'PRI', 'Puerto Rico', 'Commonwealth of Puerto Rico');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000275, 0, 1, 0, 'PS', 'PSE', 'Palestine', 'State of Palestine');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000620, 0, 1, 0, 'PT', 'PRT', 'Portugal', 'Portuguese Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000585, 0, 1, 0, 'PW', 'PLW', 'Palau', 'Republic of Palau');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000600, 0, 1, 0, 'PY', 'PRY', 'Paraguay', 'Republic of Paraguay');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000634, 0, 1, 0, 'QA', 'QAT', 'Qatar', 'State of Qatar');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000638, 0, 1, 0, 'RE', 'REU', 'Réunion', 'Overseas Region of Réunion');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000642, 0, 1, 0, 'RO', 'ROU', 'Romania', 'Romania');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000688, 0, 1, 0, 'RS', 'SRB', 'Serbia', 'Republic of Serbia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000643, 0, 1, 0, 'RU', 'RUS', 'Russia', 'Russian Federation');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000646, 0, 1, 0, 'RW', 'RWA', 'Rwanda', 'Republic of Rwanda');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000682, 0, 1, 0, 'SA', 'SAU', 'Saudi Arabia', 'Kingdom of Saudi Arabia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000090, 0, 1, 0, 'SB', 'SLB', 'Solomon Islands', 'Solomon Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000690, 0, 1, 0, 'SC', 'SYC', 'Seychelles', 'Republic of Seychelles');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000729, 0, 1, 0, 'SD', 'SDN', 'Sudan', 'Republic of the Sudan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000752, 0, 1, 0, 'SE', 'SWE', 'Sweden', 'Kingdom of Sweden');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000702, 0, 1, 0, 'SG', 'SGP', 'Singapore', 'Republic of Singapore');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000654, 0, 1, 0, 'SH', 'SHN', 'St. Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000705, 0, 1, 0, 'SI', 'SVN', 'Slovenia', 'Republic of Slovenia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000744, 0, 1, 0, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000703, 0, 1, 0, 'SK', 'SVK', 'Slovakia', 'Slovak Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000694, 0, 1, 0, 'SL', 'SLE', 'Sierra Leone', 'Republic of Sierra Leone');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000674, 0, 1, 0, 'SM', 'SMR', 'San Marino', 'Republic of San Marino');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000686, 0, 1, 0, 'SN', 'SEN', 'Senegal', 'Republic of Senegal');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000706, 0, 1, 0, 'SO', 'SOM', 'Somalia', 'Somalia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000740, 0, 1, 0, 'SR', 'SUR', 'Suriname', 'Republic of Suriname');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000728, 0, 1, 0, 'SS', 'SSD', 'South Sudan', 'South Sudan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000678, 0, 1, 0, 'ST', 'STP', 'Sao Tome and Principe', 'Democratic Republic of Sao Tome and Principe');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000222, 0, 1, 0, 'SV', 'SLV', 'El Salvador', 'Republic of El Salvador');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000534, 0, 1, 0, 'SX', 'SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000760, 0, 1, 0, 'SY', 'SYR', 'Syria', 'Syrian Arab Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000748, 0, 1, 0, 'SZ', 'SWZ', 'Eswatini', 'Kingdom of Eswatini (Swasiland)');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000796, 0, 1, 0, 'TC', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000148, 0, 1, 0, 'TD', 'TCD', 'Chad', 'Republic of Chad');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000260, 0, 1, 0, 'TF', 'ATF', 'French Southern Territories', 'Territory of the French Southern and Antarctic Lands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000768, 0, 1, 0, 'TG', 'TGO', 'Togo', 'Togolese Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000764, 0, 1, 0, 'TH', 'THA', 'Thailand', 'Kingdom of Thailand');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000762, 0, 1, 0, 'TJ', 'TJK', 'Tajikistan', 'Republic of Tajikistan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000772, 0, 1, 0, 'TK', 'TKL', 'Tokelau', 'Tokelau');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000626, 0, 1, 0, 'TL', 'TLS', 'Timor-Leste', 'Democratic Republic of Timor-Leste');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000795, 0, 1, 0, 'TM', 'TKM', 'Turkmenistan', 'Turkmenistan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000788, 0, 1, 0, 'TN', 'TUN', 'Tunisia', 'Tunisian Republic');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000776, 0, 1, 0, 'TO', 'TON', 'Tonga', 'Kingdom of Tonga');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000792, 0, 1, 0, 'TR', 'TUR', 'Turkey', 'Republic of Turkey');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000780, 0, 1, 0, 'TT', 'TTO', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000798, 0, 1, 0, 'TV', 'TUV', 'Tuvalu', 'Tuvalu');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000158, 0, 1, 0, 'TW', 'TWN', 'Taiwan', 'Taiwan, Province of China');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000834, 0, 1, 0, 'TZ', 'TZA', 'Tanzania', 'United Republic of Tanzania');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000804, 0, 1, 0, 'UA', 'UKR', 'Ukraine', 'Ukraine');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000800, 0, 1, 0, 'UG', 'UGA', 'Uganda', 'Republic of Uganda');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000581, 0, 1, 0, 'UM', 'UMI', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000840, 0, 1, 0, 'US', 'USA', 'United States of America', 'United States of America');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000858, 0, 1, 0, 'UY', 'URY', 'Uruguay', 'Oriental Republic of Uruguay');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000860, 0, 1, 0, 'UZ', 'UZB', 'Uzbekistan', 'Republic of Uzbekistan');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000336, 0, 1, 0, 'VA', 'VAT', 'Holy See', 'State of the Vatican City');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000670, 0, 1, 0, 'VC', 'VCT', 'St. Vincent and the Grenadines', 'Saint Vincent and the Grenadines');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000862, 0, 1, 0, 'VE', 'VEN', 'Venezuela', 'Bolivarian Republic of Venezuela');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000092, 0, 1, 0, 'VG', 'VGB', 'Virgin Islands (British)', 'British Virgin Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000850, 0, 1, 0, 'VI', 'VIR', 'Virgin Islands (U.S.)', 'United States Virgin Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000704, 0, 1, 0, 'VN', 'VNM', 'Viet Nam', 'Socialist Republic of Viet Nam');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000548, 0, 1, 0, 'VU', 'VUT', 'Vanuatu', 'Republic of Vanuatu');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000876, 0, 1, 0, 'WF', 'WLF', 'Wallis and Futuna', 'Collectivity of the Wallis and Futuna Islands');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000882, 0, 1, 0, 'WS', 'WSM', 'Samoa', 'Independent State of Samoa');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000887, 0, 1, 0, 'YE', 'YEM', 'Yemen', 'Republic of Yemen');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000175, 0, 1, 0, 'YT', 'MYT', 'Mayotte', 'Departmental Collectivity of Mayotte');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000710, 0, 1, 0, 'ZA', 'ZAF', 'South Africa', 'Republic of South Africa');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000894, 0, 1, 0, 'ZM', 'ZMB', 'Zambia', 'Republic of Zambia');
INSERT INTO KeyItem (id, modificationCounter, keyList, disabled, business_key, value, name, comment) VALUES (101000716, 0, 1, 0, 'ZW', 'ZWE', 'Zimbabwe', 'Republic of Zimbabwe');