-- *** KeyList (Dictionaries or key/value lists) ***
CREATE TABLE KeyList (
  id                  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
  modificationCounter INTEGER NOT NULL,
  business_key        VARCHAR (255),
  name                VARCHAR (255),
  comment             VARCHAR (4096),
  disabled            BOOLEAN,
  ordering            INTEGER NOT NULL,
  valueRequired       BOOLEAN,
  valuePattern        VARCHAR (255),
  permission          VARCHAR (255),
  cacheable           BOOLEAN,
  CONSTRAINT PK_KeyList PRIMARY KEY(id),
  CONSTRAINT UK_KeyList_key UNIQUE(business_key)
);